apiVersion: v1
kind: Secret
metadata:
  name: mongo-db-secrets
  namespace: database
type: Opaque
data:
  dbuser: bW9uZ29hZG1pbg==
  dbpass: c2VjcmV0

---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secret-provider
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "my-secret"    # AWS Secrets Manager secret name
        objectType: "secretsmanager"
