apiVersion: v1
kind: Service
metadata:
  name: mongo-db-svc
  namespace: database
spec:
  selector:
    app: mongo-db
  ports:
  - port: 27017
    targetPort: dbport
---
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: my-secret-provider
  namespace: default
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "my-secret"    # AWS Secrets Manager secret name
        objectType: "secretsmanager"
